### ISSUE TITLE
App package

### ISSUE THREAD

**Issue by chaocodecode** [Fenhua/BadmintonScoreBoard-Android#2]
According to Android developer (http://developer.android.com/guide/topics/manifest/manifest-element.html), we should not use "com.example" namespace as part of package name. At the moment, I can see the app package name is set as "com.example.android.badmintonscoreboard". Thus, we have to come up a new package name. For instance, "fi.fenhua.android.badminton.scoreboard".

**Comment by xiaofinland** [comment]
Yes, We have to change the package name to "fi.fenhua.android.badminton.scoreboard"

**Comment by chaocodecode** [comment]
OK.

AP: Change package name.
